name: ez_build
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  get: # for state management and context less stuff
  flutter_screenutil: ^5.8.4 # make app responsive
  shared_preferences: ^2.2.0 # shared preferences persistence key value store
  flutter_launcher_icons: # change app icon
  flutter_svg: # for svg icons
  flutter_animate: # for animation
  flutter_login: ^4.2.1
  font_awesome_icon_class: ^0.0.6
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2
  google_sign_in: ^6.1.6
  dots_indicator: ^3.0.0
  expandable_text: ^2.3.0
  provider: ^6.1.1
  flutter_facebook_auth: ^5.0.11
  http: ^0.13.6
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  image_picker: ^1.0.5


dev_dependencies:
  mockito:
  flutter_lints:

  integration_test:
    sdk: flutter

  flutter_test: 
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/app_icon_foreground.png"

flutter: 
  uses-material-design: true

  assets:
    - assets/images/
    - assets/vectors/
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 700

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
